### ISSUE TITLE
Allow setting host from the querystring

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multilink#126]

**Comment by JackWilb** [comment]
I don't think we need to support this, since we can't make requests to the api.multinet.app server due to CORS. Do you still think this would be useful @waxlamp

**Comment by JackWilb** [comment]
I do have this working in the `host-in-querystring` branch, but then realized I couldn't test it with the live app because of the CORS failure

**Comment by waxlamp** [comment]
How does that solve the problem? Is it a matter of pointing the app at your local multinet setup?

A lot of this should go away with the Django backend change, but I understand the need for a solution between now and then.

**Comment by JackWilb** [comment]
The app is set to point at the local dev env without the querystring parameter through env vars. This addition allows for getting data from another source. The only use case that I could think of at the moment is pointing to prod, but that's disallowed by CORS. If this is our only use case, we should probably close this issue and not support getting data from elsewhere by adding querystring arguments

**Comment by waxlamp** [comment]
I think with Django serving the API, there *may* be a way to make this work. I will get back to you on this.

OTOH, it is simpler to just statically point the app to an API and be done with it. In dev, you'd have to change your .env file and rebuild (which is no big deal, generally); in prod, you'd have to change env vars or edit `netlify.toml` (again, no big deal).

**Comment by JackWilb** [comment]
> OTOH, it is simpler to just statically point the app to an API and be done with it. In dev, you'd have to change your .env file and rebuild (which is no big deal, generally); in prod, you'd have to change env vars or edit `netlify.toml` (again, no big deal).

Agreed, let's close this for now and if there is a great urge for using the querystring in the future, we can re-open
