### ISSUE TITLE
Use multinet client library

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multilink#31]
~https://unpkg.com/multinet@0.1.0/dist/index.js~

**Comment by waxlamp** [comment]
Can you clarify what you mean by this?

**Comment by JackWilb** [comment]
Yeah, this is to implement the multinetjs package into view instead of rolling my own code. Using unpkg was your advice since I'm just using <script> tags

**Comment by waxlamp** [comment]
Ah sounds good. I'll take a look shortly.

**Comment by JackWilb** [comment]
We can likely switch this over to the multinetjs package now. We might want to add a getAllData() function to the package first and then use that to pull data here. Let me know what you think @waxlamp and id you agree we might be best to open an issue in the multinet repo for that.

**Comment by waxlamp** [comment]
What would the `getAllData()` function do? That is, what's the exact data need for view-nodelink that's not fulfilled by the existing functions in multinetjs?

**Comment by JackWilb** [comment]
We had talked about it fetching all the data without having to manually loop through different offset values. This would pull all the data and would mean that each request to the api was relatively small. The way it's implemented right now, I just increased the limit but that doesn't seem sustainable for larger data

**Comment by waxlamp** [comment]
Ok, I will work on this in multinetjs: https://github.com/multinet-app/multinet/issues/242

**Comment by JackWilb** [comment]
Closed via #87
