### ISSUE TITLE
Link nodes not properly deselecting

### ISSUE THREAD

**Issue by JakeWags** [multinet-app/multilink#331]
Linked nodes are not properly being removed from the currently highlighted nodes/links after being deselected.

See video demonstration of the issue in the boston dataset.

https://user-images.githubusercontent.com/35744963/206584487-8a9e25f1-9dde-4350-a48b-ad2078d23a44.mov

**Comment by JackWilb** [comment]
The issue here was vue 2 reactivity with javascript `Set` objects. This is fixed in vue 3, but for now I removed the sets and replaced them with arrays. There's an issue to track adding back sets, #337
