### ISSUE TITLE
Data Assignment for Node Link and Other Views

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multilink#67]
Data assignment to the node link diagram and to other views should use a "shelf-based" drag and drop approach. Here is a simple example for the node link diagram: 

![Note Mar 5, 2021](https://user-images.githubusercontent.com/2039375/76034241-a1a57980-5efb-11ea-81b4-786da9451cdf.png)

The shelf should be similar to the one in Taggle: 

![image](https://user-images.githubusercontent.com/2039375/76104539-c697fc00-5f90-11ea-889f-8e0c133efe39.png)

This should be used to (a) select the items that are shown on the nodes, (b) on the edges, (c) in a separate tabluar view. 

Also, this interface should be generic, so that it can be used with all kinds of NL visualizations.

**Comment by JackWilb** [comment]
We have a prototype of this now. Closing in favor of other, more specific issues
