### ISSUE TITLE
Add slider for edge distance 

### ISSUE THREAD

**Issue by curtislisle** [multinet-app/multilink#92]
It would be great to be able to adjust the overall scaling of edge lengths in the nodelink diagram.  This could be accomplished by adding a slider for scaling edge length and possibly also a slider for node repulsion forces.  Overall, I want to be able to scale the nodes and the edge distances.  Similar to the Vega force directed layout example: 

https://vega.github.io/vega/examples/force-directed-layout/

**Comment by JackWilb** [comment]
There is a function `getForceRadii` that we can modify to take a param from the UI
